### ISSUE TITLE
Can't build and run 

### ISSUE THREAD

**Issue by FuzzzyYeti** [jasonmzx/cppkart#8]
![Screenshot from 2024-06-27 11-07-47](https://github.com/jasonmzx/cppkart/assets/152752313/719446a3-71b6-43cd-b630-d741a2aa05e5)

I used this command lines  
sudo apt install build-essential cmak
sudo apt install libsdl2-dev
sudo apt install libbullet-dev
sudo apt install assimp-utils libassimp-dev libassimp5

and use this command line
 
cmake .. 
make 

My os is Ubuntu 22.04 LTS 

How can i fix that error ?

**Comment by jasonmzx** [comment]
Hey sorry I forgot to update the Readme, but you need to install bullet through VCPKG instead of the 'libbullet-dev' package, I'll probably update this tomorrow in the readme... sorry for the issue

If you go on the rewrite_2 branch you should be able to build & run as its still using the libbullet apt lib, but for main you need Bullet installed via VCPKG

**Comment by atharva-0123-cs** [comment]
I just removed the "CONFIG"  
find_package(Bullet REQUIRED)  # Note: Removed CONFIG
and it worked

**Comment by jasonmzx** [comment]
Updated readme to show you how to do it, pls uninstall libbullet-dev on apt, and follow the readme, hope this works!
